import type { LucideIcon } from "lucide-react";
import {
  AlarmClock,
  BookOpenCheck,
  CalendarCheck,
  CircleCheck,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  Clock,
  DoorClosed,
  DoorOpen,
  Flag,
  GraduationCap,
  Lock,
  Milestone,
  PlayCircle,
  Rocket,
  Sparkles,
  StopCircle,
  Timer,
  Trophy,
  Unlock,
} from "lucide-react";

export const ENROLLMENT_ICON_IDS = [
  "calendar-days",
  "calendar-range",
  "calendar-clock",
  "calendar-check",
  "clock",
  "alarm",
  "timer",
  "play-circle",
  "stop-circle",
  "flag",
  "check-circle",
  "rocket",
  "sparkles",
  "milestone",
  "unlock",
  "lock",
  "door-open",
  "door-closed",
  "graduation-cap",
  "book-open-check",
  "trophy",
] as const;

export type EnrollmentIconId = (typeof ENROLLMENT_ICON_IDS)[number];

export const ENROLLMENT_ICON_LABELS: Record<EnrollmentIconId, string> = {
  "calendar-days": "Calendar Days",
  "calendar-range": "Calendar Range",
  "calendar-clock": "Calendar Clock",
  "calendar-check": "Calendar Check",
  clock: "Clock",
  alarm: "Alarm",
  timer: "Timer",
  "play-circle": "Play Circle",
  "stop-circle": "Stop Circle",
  flag: "Flag",
  "check-circle": "Check Circle",
  rocket: "Rocket",
  sparkles: "Sparkles",
  milestone: "Milestone",
  unlock: "Unlock",
  lock: "Lock",
  "door-open": "Door Open",
  "door-closed": "Door Closed",
  "graduation-cap": "Graduation Cap",
  "book-open-check": "Book Open Check",
  trophy: "Trophy",
};

export const ENROLLMENT_ICON_COMPONENTS: Record<EnrollmentIconId, LucideIcon> = {
  "calendar-days": CalendarDays,
  "calendar-range": CalendarRange,
  "calendar-clock": CalendarClock,
  "calendar-check": CalendarCheck,
  clock: Clock,
  alarm: AlarmClock,
  timer: Timer,
  "play-circle": PlayCircle,
  "stop-circle": StopCircle,
  flag: Flag,
  "check-circle": CircleCheck,
  rocket: Rocket,
  sparkles: Sparkles,
  milestone: Milestone,
  unlock: Unlock,
  lock: Lock,
  "door-open": DoorOpen,
  "door-closed": DoorClosed,
  "graduation-cap": GraduationCap,
  "book-open-check": BookOpenCheck,
  trophy: Trophy,
};

export function isEnrollmentIconId(value: string): value is EnrollmentIconId {
  return ENROLLMENT_ICON_IDS.includes(value as EnrollmentIconId);
}
